name: Build ChatBot Installer

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile main.py
          move dist\main.exe output\main.exe

      - name: Download and install Inno Setup
        run: |
          choco install innosetup

      - name: Create installer with Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" inno_setup_script.iss

      - name: Upload EXE to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: output\chatbot_installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
