name: Build and Package App

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build app with PyInstaller
        run: pyinstaller --distpath ./dist --workpath ./build --specpath ./specs main.py

      - name: Download Inno Setup
        run: choco install innosetup

      - name: Create Inno Setup installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /compile "installer_script.iss"

      - name: Upload installer to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output\ChatbotAIInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
